import random
import string
import re
from urllib.parse import urlparse, quote
from requests import Request

# BASE DE DONNÉES DE SIGNATURES WAF 
# Dictionnaire structuré contenant les empreintes connues.
# Basé sur headers spécifiques, cookies de tracking et messages d'erreur dans le body.
WAF_SIGNATURES = {
    'Cloudflare': { 
        'headers': ['cf-ray', '__cfduid', 'cloudflare-cache-status', 'cdn-loop: cloudflare', 'cf-ipcountry'], 
        'cookies': ['__cfduid', '__cf_bm', '_cfuvid'], 
        'body': ['attention required! | cloudflare', 'error code: 1020', 'ray id:', 'cloudflare ray id'] 
    },
    'AWS WAF': { 
        'headers': ['x-amz-cf-id', 'x-amzn-requestid'], 
        'cookies': ['aws-waf-token'], 
        'body': ['request blocked', '403 forbidden'] 
    },
    'Akamai': { 
        'headers': ['x-akamai', 'akamai-ghost', 'edge-control', 'x-akamai-transformed'], 
        'cookies': ['ak_bmsc', 'akaas_', 'akamai'], 
        'body': ['access denied', 'akamaighost', 'akamai edge'] 
    },
    'Azure WAF': { 
        'headers': ['x-ms-ref', 'x-azure-ref', 'x-ms-request-id'], 
        'cookies': ['applicationgatewayaffinity', 'applicationgatewayaffinitycors'], 
        'body': ['azure application gateway'] 
    },
    'Google Cloud Armor': {
        'headers': ['via: 1.1 google'],
        'body': ['403. that’s an error.', 'your client does not have permission to get url']
    },
    'Fastly': {
        'headers': ['fastly-restarts', 'x-fastly-request-id', 'x-timer'],
        'cookies': ['_fastly_session'],
        'body': ['fastly error: unknown domain']
    },
    'Imperva Incapsula': { 
        'headers': ['x-cdn', 'incap-ses', 'visid_incap', 'x-iinfo', '_incap_'], 
        'cookies': ['visid_incap', 'incap_ses', '_incap_'], 
        'body': ['incapsula', 'incident id', 'powered by imperva'] 
    },
    'Sucuri': { 
        'headers': ['x-sucuri-id', 'x-sucuri-cache'], 
        'cookies': ['sucuri_cloudproxyid'], 
        'body': ['access denied - sucuri website firewall', 'sucuri cloudproxy'] 
    },
    'StackPath': { 
        'headers': ['x-sp-url', 'x-sp-var', 'x-cache-status'], 
        'cookies': [], 
        'body': ['stackpath', 'sorry, you have been blocked'] 
    },
    'F5 BIG-IP ASM': { 
        'headers': ['x-cnection', 'bigipserver', 'x-waf-event-id'], 
        'cookies': ['bigipserver', 'ts', 'f5_cspm'], 
        'body': ['the requested url was rejected', 'please consult with your administrator'] 
    },
    'Citrix NetScaler': { 
        'headers': ['ns_sig', 'citrix_ns_id', 'x-nscache'], 
        'cookies': ['ns_sig', 'citrix_ns_id', 'nsk'], 
        'body': ['violation of security policy', 'citrix netscaler'] 
    },
    'Barracuda': { 
        'headers': ['barra_counter_session', 'bncookie'], 
        'cookies': ['barra_counter_session', 'bncookie'], 
        'body': ['barracuda networks', 'intent=barracuda_limiter'] 
    },
    'FortiWeb': { 
        'headers': ['fortiweb'], 
        'cookies': ['fortiweb', 'ep_fw'], 
        'body': ['firewall.fortinet.com', 'fortiweb'] 
    },
    'Palo Alto': { 
        'headers': ['x-waf-log', 'x-paloalto-waf'], 
        'cookies': ['paloalto'], 
        'body': ['has been blocked in accordance with company policy', 'palo alto networks'] 
    },
    'SonicWall': {
        'headers': ['server: sonicwall'],
        'cookies': [],
        'body': ['this request is blocked by the sonicwall']
    },
    'Sophos UTM': {
        'headers': [],
        'cookies': [],
        'body': ['powered by sophos', 'sophos web protection']
    },
    'ModSecurity (OWASP CRS)': { 
        'headers': ['mod_security', 'modsecurity'], 
        'cookies': [], 
        'body': ['not acceptable', '406 not acceptable', '403 forbidden', 'mod_security'] 
    },
    'Wordfence': { 
        'headers': [], 
        'cookies': ['wfvt_', 'wordfence_verifiedhuman'], 
        'body': ['generated by wordfence', 'your access to this site has been limited'] 
    },
    'Nginx Generic WAF': { 
        'headers': ['server: nginx'], 
        'cookies': [], 
        'body': ['403 forbidden', '406 not acceptable'] 
    },
    'Apache Generic WAF': { 
        'headers': ['server: apache'], 
        'cookies': [], 
        'body': ['403 forbidden', '406 not acceptable'] 
    }
}

def generate_random_string(length=8):
    """Génère une chaîne aléatoire pour contourner les caches."""
    return ''.join(random.choices(string.ascii_letters + string.digits, k=length))

def match_signatures(response, heuristic=False):
    """
    Analyse Passive : Compare la réponse HTTP aux signatures de la base.
    Vérifie Headers, Cookies et Body.
    """
    detected = set()
    if not response: return []
    
    h_str = str(response.headers).lower()
    c_str = str(response.cookies.get_dict()).lower()
    b_str = response.text.lower()

    for name, sigs in WAF_SIGNATURES.items():
        # 1. Vérification des Headers
        if any(s in h_str for s in sigs.get('headers', [])): 
            detected.add(f"{name} (Header)")
        # 2. Vérification des Cookies
        if any(s in c_str for s in sigs.get('cookies', [])): 
            detected.add(f"{name} (Cookie)")
        # 3. Vérification du Body (Souvent la page de blocage du WAF)
        if heuristic or response.status_code >= 400:
            if any(s in b_str for s in sigs.get('body', [])): 
                detected.add(f"{name} (Body)")
                
    return list(detected)

def probe_behavior(engine, target):
    """
    Analyse Active : Envoie des payloads provocateurs pour forcer le WAF à réagir.
    Permet de déterminer si le WAF est en mode bloquant ou passif.
    """
    
    parsed = urlparse(target)
    base_url = f"{parsed.scheme}://{parsed.netloc}{parsed.path}"
    if not base_url.endswith('/'): base_url += '/'
    
    separator = "&" if "?" in target else "?"
    rnd_param = generate_random_string()
    
    status = "Passif (Non-Bloquant)"
    normalization = "Non détectée"
    
    # Codes HTTP typiques d'un blocage WAF 
    BLOCK_CODES = [400, 403, 406, 500, 501]

    # TEST 1 : Payload Simple 
    # Payload XSS classique. La lib 'requests' va l'encoder URL automatiquement.
    payload_1 = "<script>alert(1)</script>"
    params_1 = {rnd_param: payload_1}
    
    if engine.config['verbose']:
        print(f"[NET] Test 1 (Standard) sur {target} avec {params_1}")

    resp1 = engine._send_request(base_url, method="GET", params=params_1)
    
    detected_names = []

    if resp1 is not None:
        if engine.config['verbose']:
            print(f"[DEBUG] Réponse Test 1 : Code {resp1.status_code}")
        
        # Analyse des signatures dans la réponse provoquée
        detected_names.extend(match_signatures(resp1, heuristic=True))
        
        if resp1.status_code in BLOCK_CODES:
            status = f"Actif/Bloquant (Code {resp1.status_code})"
            # Heuristique : Si Nginx renvoie une erreur sur un payload, c'est souvent un WAF configuré dessus
            if "nginx" in str(resp1.headers).lower() and not detected_names:
                detected_names.append("ModSecurity / Nginx WAF (Heuristic)")

    # TEST 2 : Double Encodage (Contournement & Normalisation)
    # Payload avec double URL encoding. Certains WAF décodent une fois, d'autres deux.
    # On construit l'URL manuellement pour empêcher 'requests' de ré-encoder.
    payload_double = "%253Cscript%253Ealert(1)%253C/script%253E"
    test_url_2 = f"{base_url}{separator}{rnd_param}={payload_double}"
    
    try:
        if engine.config['verbose']:
            print(f"[NET] Test 2 (Manual): {test_url_2}")

        req = Request('GET', test_url_2)
        prepped = engine.session.prepare_request(req)
        prepped.url = test_url_2 # Force l'URL brute
        
        resp2 = engine.session.send(prepped, verify=False, allow_redirects=True)
        
        if resp2 is not None:
            if engine.config['verbose']:
                print(f"[DEBUG] Réponse Test 2 : Code {resp2.status_code}")

            if resp2.status_code in BLOCK_CODES:
                # Si bloqué ici, le WAF a décodé l'input -> Normalisation active
                normalization = "Active (Le WAF décode les entrées)"
                
                if "Passif" in status:
                    status = f"Actif/Bloquant (Via Normalisation - Code {resp2.status_code})"
                    detected_names.extend(match_signatures(resp2, heuristic=True))
                    if "nginx" in str(resp2.headers).lower() and not detected_names:
                        detected_names.append("ModSecurity / Nginx WAF (Heuristic)")
                    
    except Exception as e:
        if engine.config['verbose']: print(f"[DEBUG] Erreur envoi brut Test 2: {e}")

    return status, normalization, list(set(detected_names))

def detect_waf(engine):
    """Fonction principale qui orchestre la détection."""
    target = engine.config['target']
    
    # 1. Baseline : Requête saine pour comparer
    base_resp = engine._send_request(target, method="GET")
    
    if not base_resp:
        return {'name': 'Inaccessible', 'behavior': {'status': 'N/A'}}

    # 2. Identification Passive
    passive_names = match_signatures(base_resp)
    
    # 3. Identification Active
    status, normalization, active_names = probe_behavior(engine, target)
    
    # 4. Agrégation des résultats
    all_names = list(set(passive_names + active_names))
    
    waf_name = "Aucun WAF détecté"
    if all_names:
        waf_name = ", ".join(all_names)
    
    # Heuristique de dernier recours : si ça bloque mais sans signature connue
    if "Bloquant" in status and "Aucun" in waf_name:
         waf_name = "Generic WAF (Comportemental)"

    return {
        'name': waf_name,
        'behavior': {
            'status': status,
            'normalization': normalization
        }
    }
